### ISSUE TITLE
Matrix room seems to be inaccessible

### ISSUE THREAD

**Issue by ginkel** [IndeedNotJames/matrix-sip-bridge#1]
Hi there,

thanks for developing this bridge! When attempting to join the official Matrix room mentioned in the README, I unfortunately get the following error:

![image](https://user-images.githubusercontent.com/174129/182041593-088baed8-491c-444b-aa81-a48fdfc75d5b.png)

Any ideas?

Thanks,
Thilo

**Comment by emilylange** [comment]
Hi :sweat_smile: 

I am currently doing some maintenance, restoring and tests on 2 of my _private_ homeservers and haven't really considered that this yields that room alias broken.
Sorry for that^^

You could try joining it via https://matrix.to/#/#matrix-sip-bridge-indeednotjames:matrix.org in the meantime :)

**Comment by emilylange** [comment]
[#matrix-sip-bridge:indeednotjames.com](https://matrix.to/#/#matrix-sip-bridge:indeednotjames.com) should work again since a few days :)

I'll close the issue for now, but let me know if something is still not working as expected.
